### ISSUE TITLE
What is use case of this plugin?

### ISSUE THREAD

**Issue by jitendravyas** [hudochenkov/postcss-not-x-child#1]

**Comment by hudochenkov** [comment]
Do exactly what readme says. It's quite useless.

**Comment by jitendravyas** [comment]
Yes but i didn't get the purpose of getting this output `div:not(:first-child) {
}`

**Comment by hudochenkov** [comment]
For example you have a menu, and you need to set space between items. You don't need extra space before first item, only between items.

```html
<ul class="nav">
	<li class="nav__item">Item 1</li>
	<li class="nav__item">Item 2</li>
	<li class="nav__item">Item 3</li>
	<li class="nav__item">Item 4</li>
	<li class="nav__item">Item 5</li>
</ul>
```

You can set space for every item and then reset space for the first item:


```css
.nav__item {
	margin-top: 10px;
}
.nav__item:first-child {
	margin-top: 0;
}
```

Or instead you can set space for every item except the first one, so you don't need override anything:

```css
.nav__item:not(:first-child) {
	margin-top: 10px;
}
```
